baseurl = "http://www.rayheberer.ai"
languageCode = "en-US"
title = "Ray Heberer"
# Enable comments by entering your Disqus shortname
disqusShortname = "rayheberer-netlify-com"
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
theme = "hugo-theme-dream"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  motto = "Motto"
  avatar = "/img/profile-122017.jpg"
  author = "Ray Heberer"
  description = "Dreams of a wild neural network"

  email = "ray.heberer@gmail.com"
  github = "https://github.com/rayheberer/"
  linkedin = "https://www.linkedin.com/in/rayheberer"
  # codepen = ""
  # stackoverflow = ""
