baseurl = "http://www.rayheberer.ai"
languageCode = "en-US"
theme = "hyde-hyde"

# Enable comments by entering your Disqus shortname
disqusShortname = "rayheberer-netlify-com"
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""

[params]
    authorimage = "/img/profile-122017.jpg"
    author = "Ray Heberer"
    title = "Ray Heberer"
    description = "Dreams of a wild neural network"
  
    dateformat = "Jan 1, 2006"
    highlightjs = true

[params.social]
    github = "rayheberer"
    instagram = "ray_heberer"
    #xing = "<username>"
    linkedin = "rayheberer"
    twitter = "rayheberer4"
    #facebook = "<username>"
    #stackoverflow = "<username>"
    email = "ray.heberer@gmail.com"
